org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=768m -XX:ReservedCodeCacheSize=256m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.workers.max=4
org.gradle.vfs.watch=false
org.gradle.warning.mode=none
android.useAndroidX=true
kotlin.incremental=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
